services:
  - type: web
    name: vaivahikam-api
    runtime: node
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    plan: starter
    envVars:
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
